import Head from "next/head";
import type { NextPage } from 'next'
import dynamic from "next/dynamic";

const Hero: NextPage = () => {
  return (

    <div>
      <Head>
        <title>New Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='text-5xl text-blue-700'> Coffee <span className="text-white">Connoisseur</span></h1>
      <p className='text-xl'>Discover your local coffee shops!</p>
      <button className=' bg-blue-800 w-40 h-10'>View stores nearby</button>
    </div>
  );
};

export default Hero;
