import Head from "next/head";

const first = () => {
  return (
    <div>
      <Head>
        <title>New Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      New Next Component
    </div>
  );
};

export default first;
