import Head from "next/head";
import type { NextPage } from 'next'

const First: NextPage= () => {
  return (
    <div>
      <Head>
        <title>New Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      New Next Component
    </div>
  );
};

export default First;
